version: "3.7"

services:
  postgresql:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - 5432:5432
    networks:
      - coffeeshop-network

  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - coffeeshop-network

  product-service:
    image: ghcr.io/thangchung/coffeeshop-on-nomad/product-service:0.1.2
    build:
      context: .
      dockerfile: ./src/ProductService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UseTracingExporter=console1
      - UseMetricsExporter=console1
      - UseLogExporter=console1
      - AspNetCoreInstrumentation__RecordException=true
    ports:
      - "5001:5001"
    restart: always
    networks:
      - coffeeshop-network
  
  counter-service:
    image: ghcr.io/thangchung/coffeeshop-on-nomad/counter-service:0.1.2
    build:
      context: .
      dockerfile: ./src/CounterService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__counterdb=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd
      - ProductApiUri=http://product-service:5001
      - RabbitMqUrl=rabbitmq
      - UseTracingExporter=console1
      - UseMetricsExporter=console1
      - UseLogExporter=console1
      - AspNetCoreInstrumentation__RecordException=true
    ports:
      - "5002:5002"
    depends_on:
      - postgresql
      - rabbitmq
      - product-service
    restart: always
    networks:
      - coffeeshop-network

  barista-service:
    image: ghcr.io/thangchung/coffeeshop-on-nomad/barista-service:0.1.2
    build:
      context: .
      dockerfile: ./src/BaristaService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__baristadb=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd
      - RabbitMqUrl=rabbitmq
      - UseTracingExporter=console1
      - UseMetricsExporter=console1
      - UseLogExporter=console1
      - AspNetCoreInstrumentation__RecordException=true
    ports:
      - "5003:5003"
    depends_on:
      - postgresql
      - rabbitmq
    restart: always
    networks:
      - coffeeshop-network

  kitchen-service:
    image: ghcr.io/thangchung/coffeeshop-on-nomad/kitchen-service:0.1.2
    build:
      context: .
      dockerfile: ./src/KitchenService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__kitchendb=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=P@ssw0rd
      - RabbitMqUrl=rabbitmq
      - UseTracingExporter=console1
      - UseMetricsExporter=console1
      - UseLogExporter=console1
      - AspNetCoreInstrumentation__RecordException=true
    ports:
      - "5004:5004"
    depends_on:
      - postgresql
      - rabbitmq
    restart: always
    networks:
      - coffeeshop-network

  reverse-proxy:
    image: ghcr.io/thangchung/coffeeshop-on-nomad/reverse-proxy:0.1.2
    build:
      context: .
      dockerfile: ./src/ReverseProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__productApiCluster__Destinations__destination1__Address=http://product-service:5001
      - ReverseProxy__Clusters__counterApiCluster__Destinations__destination1__Address=http://counter-service:5002
      - UseTracingExporter=console1
      - UseMetricsExporter=console1
      - UseLogExporter=console1
      - AspNetCoreInstrumentation__RecordException=true
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - counter-service
      - barista-service
      - kitchen-service
    restart: always
    networks:
      - coffeeshop-network

  datagen-app:
    image: ghcr.io/thangchung/coffeeshop-on-nomad/datagen-app:0.1.2
    build:
      context: .
      dockerfile: ./src/DataGen/Dockerfile
    environment:
      - CoffeeShopApi=http://reverse-proxy:8080
      - SubmitOrderRoute=/counter-api/v1/api/orders
    depends_on:
      - reverse-proxy
    restart: always
    networks:
      - coffeeshop-network

  # plantuml-server:
  #   image: "plantuml/plantuml-server:jetty"
  #   environment:
  #     PLANTUML_LIMIT_SIZE: 24384
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - coffeeshop-network

networks:
  coffeeshop-network:
