name: Publish Docker Image

on:
  push:
    branches:
      - master
      - feat/*

jobs:
  push_to_gpr:
    name: Push Docker image to GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.100-rc.1.22431.12

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Fetch version
        shell: bash
        run: |
          # Restore .NET tools
          dotnet tool restore

          # Get the version number
          echo "VERSION=$(dotnet minver -t v -m 0.1 --default-pre-release-phase preview -v e -d ./src/CounterService)" >> $GITHUB_ENV

      - name: CounterService - Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/counter-service
          tags: |
            type=raw,value=${{ env.VERSION }}
          flavor: |
            latest=true

      - name: CounterService - Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./src/CounterService/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}